export function generateMediaPrompt(filepath) {
	return [
		'Analyze this file path and extract media information:\n',
		`Full path: ${filepath}\n`,
		'Return a JSON object with the following structure, including only relevant fields for the media type:',
		'```jsonc',
		'{',
		'  "path": string,     // Full file path',
		'  "type": string,     // One of: movie, show, book, comic, music, audiobook, subtitle',
		'  "title": string,    // Main title of the content',
		'  "year": number,     // Release/publication year',
		'  "quality": string,  // Video quality/resolution (for video files)',
		'  "codec": string,    // Video/audio codec',
		'  "format": string,   // File format/extension',
		'  "season": number,   // Season number (for TV shows)',
		'  "episode": number,  // Episode number (for TV shows)',
		'  "series": string,   // Series name (for shows/books/comics)',
		'  "issue": number     // Issue number (for comics)',
		'}',
		'```',
		'Examples:\n',
		'1. Movie file:',
		'```json\n{',
		'  "path": "/media/movies/The Matrix (1999) 1080p.mkv",',
		'  "type": "movie",',
		'  "title": "The Matrix",',
		'  "year": 1999,',
		'  "quality": "1080p",',
		'  "format": "mkv"',
		'}\n```\n',
		'2. TV Show episode:',
		'```json\n{',
		'  "path": "/media/shows/The Office/Season 1/S01E01 - Pilot.mp4",',
		'  "type": "show",',
		'  "title": "Pilot",',
		'  "series": "The Office",',
		'  "season": 1,',
		'  "episode": 1,',
		'  "format": "mp4"',
		'}\n```\n',
		'3. Comic book:',
		'```json\n{',
		'  "path": "/media/comics/Batman/Batman #001.cbr",',
		'  "type": "comic",',
		'  "title": "Batman",',
		'  "series": "Batman",',
		'  "issue": 1,',
		'  "format": "cbr"',
		'}\n```\n',
		'Please analyze the provided file path and return a JSON object with appropriate fields based on',
		'the media type. Include only relevant fields and ensure all values are of the correct type (string, number).',
		'}'
	].join('\n')
}
